export let legendLayers = {
    "Существующая велоинфраструктура":
        '<div class="leaflet-control-layer-legend"><table><tbody><tr><td style="text-align: center;"><img src="sourcedata/legend/_6_Существующаявелосипеднаяполоса0.png"></td><td>Существующая велосипедная полоса</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/_6_Существующаявелосипеднаядорожка1.png"></td><td>Существующая велосипедная дорожка</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/_6_Существующаявелопешеходнаядорожка2.png"></td><td>Существующая велопешеходная дорожка</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/_6_Существующаяполосадляобщественноготранспорта3.png"></td><td>Существующая полоса для общественного транспорта</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/_6_Существующеевелосипедноепересечение5.png"></td><td>Существующее велосипедное пересечение</td></tr></tbody></table></div>',
    "Планируемая велоинфраструктура":
        '<div class="leaflet-control-layer-legend"><table> <tbody> <tr> <td style="text-align: center;"><img src="sourcedata/legend/_5.png"></td> <td>Планируемые велосипедные пути</td> </tr> </tbody> </table></div>',
    "Схема развития ОТСлаб":
        '<div class="leaflet-control-layer-legend"><table><tbody><tr><td style="text-align: center;"><img src="sourcedata/legend/_4_Предлагаемаявелосипеднаяполоса0.png"></td><td>Предлагаемая велосипедная полоса</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/_4_Предлагаемаявелосипеднаядорожка1.png"></td><td>Предлагаемая велосипедная дорожка</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/_4_Предлагаемаявелопешеходнаядорожка2.png"></td><td>Предлагаемая велопешеходная дорожка</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/_4_Предлагаемаяполосадляобщественноготранспорта3.png"></td><td>Предлагаемая полоса для общественного транспорта</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/_4_Предлагаемаявелосипеднаязона4.png"></td><td>Предлагаемая велосипедная зона</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/_4_Предлагаемыйнавигационныймаршрут5.png"></td><td>Предлагаемый навигационный маршрут</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/_4_Предлагаемоевелосипедноепересечение6.png"></td><td>Предлагаемое велосипедное пересечение</td></tr></tbody></table></div>',
    "Стратегическая схема ГЦУП":
        '<div class="leaflet-control-layer-legend"><table> <tbody> <tr> <td style="text-align: center;"><img src="sourcedata/legend/_3_ПерспективныеЕГПП1.png"></td> <td>Перспективные/ЕГПП</td> </tr> </tbody> </table></div>',
    "Велосипедизация СПб – план":
        '<div class="leaflet-control-layer-legend"><table><tbody><tr><td style="text-align: center;"><img src="sourcedata/legend/2015_2_выездыизгорода0.png"></td><td>выезды из города</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/2015_2_загородныесвязиипродолжения1.png"></td><td>загородные связи и продолжения</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/2015_2_маршрутыгородскогозначенияивыше2.png"></td><td>маршруты городского значения и выше</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/2015_2_маршрутырайонногозначения3.png"></td><td>маршруты районного значения</td></tr><tr><td style="text-align: center;"><img src="sourcedata/legend/2015_2_стройпроект4.png"></td><td>стройпроект</td></tr></tbody></table></div>',
    "Исследование «Восприятие поездок на велосипеде», ИТМО, 2022":
        '<div class="leaflet-control-layer-legend"> <div style="display: flex; flex-direction: column; align-items: center;"> <div style="margin-bottom: 3px;">Плотность маршрутов</div> <div>0</div> <div style="display: flex; flex-direction: row; justify-content: center; align-items: center;"> <div style="width: 75px; text-align: right; margin: 0 5px;">Хорошие</div> <div style="width: 10px; height: 100px; margin: 2px 1px; background: linear-gradient(#f7fcf5,#e5f5e0,#c7e9c0,#a1d99b,#74c476,#41ab5d,#238b45,#006d2c,#00441b);"> </div> <div style="width: 10px; height: 100px; margin: 2px 1px; background: linear-gradient(#fff5f0,#fee0d2,#fcbba1,#fc9272,#fb6a4a,#ef3b2c,#cb181d,#a50f15,#67000d);"> </div> <div style="width: 75px; text-align: left; margin: 0 5px;">Плохие</div> </div> <div>25</div> </div> </div>',
};
